export const NFTs = [
    {
      Id: 1,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Bone Punkzz.jpg",
      Edition: 371,
      Stock: 0,
      Title: "Bone Punkzz",
      Price: " 1 $ICP",
  
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 2,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Bone Punkzz.jpg",
      Edition: 371,
      Stock: 128,
      Title: "Bone Punkzz",
      Price: "1 $ICP",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 3,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Bone Punkzz.jpg",
      Edition: 371,
      Stock: 128,
      Title: "Bone Punkzz",
      Price: "1 $ICP",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 4,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Bone Punkzz.jpg",
      Edition: 371,
      Stock: 128,
      Title: "Bone Punkzz",
      Price: "1 $ICP",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 5,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Bone Punkzz.jpg",
      Edition: 371,
      Stock: 128,
      Title: "Bone Punkzz",
      Price: "1 $ICP",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 6,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Bone Punkzz.jpg",
      Edition: 371,
      Stock: 128,
      Title: "Bone Punkzz",
      Price: "1 $ICP",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
  ];
  