export const NFTs = [
    {
      Id: 1,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Thumbnail.png",
      Edition: 371,
      Stock: 0,
      Title: "Racing Snails 001",
      Price: "50 FTM",
  
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 2,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Thumbnail.png",
      Edition: 371,
      Stock: 128,
      Title: "Racing Snails 002",
      Price: "50 FTM",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 3,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Thumbnail.png",
      Edition: 371,
      Stock: 128,
      Title: "Racing Snails 003",
      Price: "50 FTM",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 4,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Thumbnail.png",
      Edition: 371,
      Stock: 128,
      Title: "Racing Snails 004",
      Price: "50 FTM",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 5,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Thumbnail.png",
      Edition: 371,
      Stock: 128,
      Title: "Racing Snails 005",
      Price: "50 FTM",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 6,
      Badge: "Total Sale: $82,571",
      ImageUrl: "/images/Thumbnail.png",
      Edition: 371,
      Stock: 128,
      Title: "Racing Snails 006",
      Price: "50 FTM",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
  ];
  